environment: development
api:
  host: https://apis.example.com
database:
  url: postgresql://postgres:5432/hackathon_db?sslmode=disable
  username: pguser
  password: pgpassword
spotify:
  clientid: cedec6852cff43f38901967beae457eb
  clientsecret: a88a1562e80f4e9084209aed3ea13fab
  tokenurl: https://accounts.spotify.com/api/token
  host: https://api.spotify.com
