version: '2.1'

services:
  migration:
    image: boxfuse/flyway:5.2.3-alpine
    volumes:
      - ./migrations/sql:/flyway/sql
      - ./migrations/flyway.conf:/flyway/conf/flyway.conf
    command: ["-url=jdbc:postgresql://postgres:5432/hackathon_db?useUnicode=true&characterEncoding=utf8&useSSL=false", "-user=postgres", "-password=pgpassword", "migrate"]
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    volumes:
      - ./development/database/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: rest-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=hackathon_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    ports:
      - "9091:8080"
    links:
      - postgres
      - model
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_started
    container_name: backend
  mood-model:
    image: isabelly/mood_model:v1
    ports:
      - "9092:5000"
    container_name: mood-model
  predict-model:
    image: isabelly/predict_model:v1
    ports:
      - "9093:5000"
    container_name: predict-model
